### ISSUE TITLE
 I Think Therefore ICANN: An RPG about TLDs

### ISSUE THREAD

**Issue by lifewinning** [chootka/radical-networks#25]
## I Think Therefore ICANN: An RPG about TLDs

Name : Ingrid Burrington & Surya Mattu
Location : Brooklyn, NY
Email : lifewinning@gmail.com, surya@suryamattu.com
Twitter : @lifewinning, @suryamattu
GitHub : @lifewinning, @samatt
Url(s) : 
## Type of proposal

Workshop
## Description of your talk / panel / workshop / demo

Domain names are where the politics, poetics, and peculiarities of the web express themselves in often the most direct and clever ways. But even the most active domain name hoarder might not really understand how the Domain Name System works, why certain TLDs exist, and how they at times become an arena where real-world geopolitical conflicts play out online. 

This is a workshop about understanding the technical structures behind the weird and deeply political world of domain names via a live-action roleplaying game. We'll begin with an overview of DNS, ICANN, the TLD creation process, engage in some roleplaying scenarios based on real-world incidents in ICANN history, and brainstorm alternative models to the current model for network naming conventions. Somewhere between Risk, D&D, Model UN, and TRON. 
## Length of talk / panel / workshop

1.5hrs
## Workshop technical requirements and materials list

[For workshops, include technical requirements, the maximum number of attendees and a full list of materials needed for attendees.]
- Max 15 participants
- Projector for some slides would be useful
- Tables and chairs
## Speaker Bio

https://avatars3.githubusercontent.com/u/1969578?v=3&s=256
https://www.dropbox.com/s/biexqdrf3d6kkpb/oh_for_sure_man.jpg?dl=0

Surya and Ingrid promise they'll write a bio later.

**Comment by allisonburtch** [comment]
that title though :star: :+1:
